// TypeScript port of python/retina/model/viewport_state.py (transforms and zoom).
//
// The domain stays the source of truth: the local camera exists only to render pan and
// zoom at 60 FPS without a server round trip. At the end of each gesture, the client pushes its
// state through `app.set_viewport` — a single Python echo per gesture, clean and replayable,
// rather than an avalanche during the drag.
//
// The formulas are copied from viewport_state.py:149-214 and checked against values
// produced by the real ViewportState (web/tests/camera.test.ts, fixtures generated by
// scripts/gen_web_fixtures.py).

export type Point = readonly [number, number];

/** Zoom bounds — identical to the domain's _MIN_ZOOM / _MAX_ZOOM. */
export const MIN_ZOOM = 1 / 64;
export const MAX_ZOOM = 64;

export function clampZoom(zoom: number): number {
  return Math.min(Math.max(zoom, MIN_ZOOM), MAX_ZOOM);
}

export class Camera {
  zoom = 1;
  center: Point = [0, 0];
  /** Viewport size in device-independent pixels (as in ViewportState.vw/vh). */
  vw = 1;
  vh = 1;
  dpr = 1;

  constructor(
    public imageWidth: number,
    public imageHeight: number,
  ) {
    this.center = [imageWidth / 2, imageHeight / 2];
  }

  setImageSize(width: number, height: number): void {
    this.imageWidth = width;
    this.imageHeight = height;
  }

  updateGeometry(vw: number, vh: number, dpr = 1): void {
    this.vw = vw;
    this.vh = vh;
    this.dpr = dpr;
  }

  /** Sets the zoom. With `pivot` (image coords), that point stays still on screen. */
  setZoom(zoom: number, pivot?: Point): void {
    const next = clampZoom(zoom);
    if (pivot) {
      const ratio = this.zoom / next;
      this.center = [
        pivot[0] + (this.center[0] - pivot[0]) * ratio,
        pivot[1] + (this.center[1] - pivot[1]) * ratio,
      ];
    }
    this.zoom = next;
  }

  setCenter(center: Point): void {
    this.center = [center[0], center[1]];
  }

  /** Shifts the view by a screen displacement (mouse drag). */
  panByViewport(dx: number, dy: number): void {
    this.center = [this.center[0] - dx / this.zoom, this.center[1] - dy / this.zoom];
  }

  zoomToFit(allowMagnification = false): void {
    if (this.imageWidth <= 0 || this.imageHeight <= 0 || this.vw <= 0 || this.vh <= 0) return;
    let fit = Math.min(this.vw / this.imageWidth, this.vh / this.imageHeight);
    if (!allowMagnification) fit = Math.min(fit, 1);
    this.zoom = clampZoom(fit);
    this.center = [this.imageWidth / 2, this.imageHeight / 2];
  }

  /** Image point → viewport point (device-independent px), y downwards. */
  imageToViewport(pt: Point): Point {
    return [
      (pt[0] - this.center[0]) * this.zoom + this.vw / 2,
      (pt[1] - this.center[1]) * this.zoom + this.vh / 2,
    ];
  }

  /** Image length → screen length (counterpart of `ViewportState.image_scalar_to_viewport`). */
  imageScalarToViewport(scalar: number): number {
    return scalar * this.zoom;
  }

  /** Algebraic inverse of the previous one. */
  viewportToImage(pt: Point): Point {
    return [
      (pt[0] - this.vw / 2) / this.zoom + this.center[0],
      (pt[1] - this.vh / 2) / this.zoom + this.center[1],
    ];
  }

  /**
   * Image → clip space matrix, column-major for GLSL.
   *
   * Composition of imageToViewport then viewport → clip. The Y axis is flipped (`-2/vh`) because
   * the image reads top to bottom whereas clip space goes up: this is the equivalent of the
   * `flip=(False, True, False)` of the VisPy camera in the former Qt shell.
   */
  clipMatrix(): Float32Array {
    const sx = (2 * this.zoom) / this.vw;
    const sy = (-2 * this.zoom) / this.vh;
    return new Float32Array([
      sx, 0, 0,
      0, sy, 0,
      -this.center[0] * sx, -this.center[1] * sy, 1,
    ]);
  }
}
