"""The concrete processes shipped. The imports trigger registration (@register).

Every module imports its heavy libraries LAZILY (inside the methods), so that
``import retina`` works without the ``[astro]`` extra.
"""

from . import (
    ai,
    alpha,
    analysis,
    astrometry,
    background,
    calibration,
    catalogs,
    channels,
    color,
    comet,
    convolution,
    cosmetic,
    curves,
    dbe,
    debayer,
    decompose,
    denoise,
    detection,
    ephemeris,
    estimation,
    fourier,
    galaxy,
    geometry,
    gradient,
    hdr,
    histogram,
    icc,
    inspection,
    integration,
    lightcurve,
    linearpattern,
    localnorm,
    masks,
    mosaic,
    multiscale,
    narrowband,
    noise,
    photometric,
    photometry,
    pixelmath,
    preprocess,
    psf,
    registration,
    restore,
    retouch,
    script,
    starremoval,
    stars,
    statistics,
    stretch,
    subframe,
    utility,
    wavelet,
)

__all__ = [
    "ai",
    "alpha", "analysis",
    "astrometry", "background", "calibration", "catalogs", "channels", "color", "comet",
    "convolution",
    "cosmetic", "curves", "dbe", "debayer", "decompose", "denoise", "detection", "ephemeris",
    "estimation", "fourier", "galaxy", "geometry", "gradient", "hdr", "histogram", "icc",
    "inspection", "integration", "lightcurve", "linearpattern", "localnorm",
    "masks", "mosaic", "multiscale",
    "narrowband", "noise",
    "photometric", "photometry", "pixelmath", "preprocess", "psf", "registration",
    "restore", "retouch",
    "script", "starremoval", "stars", "statistics", "stretch", "subframe", "utility",
    "wavelet",
]
